-- Update Women's Month Hike route with polyline, distance, and elevation data
-- (extracted from Lingguhob Campsite GPX / Strava route 3467575946256382810)

UPDATE event_routes
SET
  summary_polyline = 'sbaaAskgiVXiAX[s@aC?qA[g@Oa@SwAcA_AOeBWYk@Ae@c@yB{AUUk@Yi@JOKIAKRYTMBcAj@Q^U@GJG@MLSHY\?HM??DI?EPGDII[CAAA[MO?EWCMMKEBEKMGC?DYq@MKOEMMS@OJAQKMAUSa@EQQ?CSDQGOASJM@QDQASHO@QW]CSY]QGESMHOe@SBOIQEEQOEGOMQOGSAKKEe@KMQGMMOGQA@SKMIc@GPLMOGLLg@BU?QIQCMOPJQ@QC[XQBS_@QEe@BIOASQ?GOMKSCMISAc@JQHQES@OKISe@KAQOKOJGQ_@SENAQOGMM@e@]UFOh@e@EQS@QAe@DQAQDOES?a@KQ?QEMJc@DQHMJINOHk@d@}@l@WZIN]TGPAPEPNJBRKPYVAP[TS?GOSGQ@NFJNMLe@CHNc@FKNOFIb@Ob@MJQDGPMJDPNJa@Nc@@GPOHc@JFPKNc@Fs@Ta@j@EP@Ro@AADWn@k@~@u@x@Yh@[fAo@jAY~Bq@`Ak@n@q@Li@n@iB|@Kh@IJc@V}AvBW`@q@DaAP[lAEtAYl@eAV]P_B?WP[d@?A]l@MhAWRMl@CrAU\a@NUb@Mr@GtDQ`AGlAQjBKZSZm@ZWA[KI`@IPS^OHGPS^Ef@@f@Q`@AP?RCd@KJINOJGOQGKNc@NQ??POFEROa@Ec@Ce@Dg@MMMKSCOIe@GQ@QABI',
  distance = 5197,
  elevation_gain = 625
WHERE strava_route_id = 3467575946256382810;
